POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Unite Summit Danillooo",
    "details": "Um evento para quem é apaixonado por programaçao",
    "maximumAttendees": 100
}