POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Novo evento",
    "details": null,
    "maximumAttendees": 1
}

###

POST http://localhost:3333/events/005831fa-6fd3-40c6-980e-a2c3db5eb756/attendees
Content-Type: application/json

{
    "name": "Danilo Leal",
    "email": "danilo2@noulsolutions.com"
}

###

GET http://localhost:3333/events/5d9b0260-be4b-459d-955a-df21bbf4a6c4

###

GET http://localhost:3333/attendees/2/badge

###

GET http://localhost:3333/attendees/2/check-in

###

GET http://localhost:3333/events/005831fa-6fd3-40c6-980e-a2c3db5eb756/attendees